spring:
  kafka:
    consumer:
      auto-offset-reset: earliest
    listener:
      ack-mode: MANUAL_IMMEDIATE


dubbo:
  application:
    id: dubbo-consumer-demo
    name: dubbo-consumer-demo
    logger: slf4j
person:
  name: gaga
  age: 46