#spring:
#  kafka:
#    consumer:
#      auto-offset-reset: earliest
#    listener:
#      ack-mode: MANUAL_IMMEDIATE


dubbo:
  application:
    id: dubbo-consumer-demo
    name: spring_demo
    logger: slf4j
person:
  name: gaga
  age: 46
tennis:
  wta: https://api.wtatennis.com/tennis/players/ranked?pageSize=100&type=rankSingles&sort=asc&name=&metric=SINGLES&at=